language:
    csharp
sudo: required
mono: none 
dotnet: 3.0

os:
  - linux

global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=true

before_script:
    - dotnet restore Dramarr.Data/Dramarr.Data.csproj
    - dotnet restore Dramarr.Data.Tests/Dramarr.Data.Tests.csproj
    
script:
    - dotnet build Dramarr.Data/Dramarr.Data.csproj
    - dotnet build Dramarr.Data.Tests/Dramarr.Data.Tests.csproj
    - dotnet test Dramarr.Data.Tests/Dramarr.Data.Tests.csproj